AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: sam_test_lambdafunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: ./
      Timeout: 30
